// Random person names for quick testing — Old English / Frankish / Germanic flavour.
// ponytail: a flat pair of lists, not a generator; swap in per-culture lists when cultures exist.

const MALE = [
  'Æthelred',
  'Æthelstan',
  'Alfred',
  'Beorhtric',
  'Beornwulf',
  'Cenwulf',
  'Ceolwulf',
  'Cuthbert',
  'Dunstan',
  'Eadric',
  'Eadwig',
  'Ecgberht',
  'Godwin',
  'Harold',
  'Leofric',
  'Osric',
  'Oswald',
  'Sigeberht',
  'Wulfhere',
  'Wulfstan',
  'Adalbert',
  'Arnulf',
  'Baldwin',
  'Berengar',
  'Childeric',
  'Chlodomer',
  'Clovis',
  'Dagobert',
  'Ebroin',
  'Guntram',
  'Hildebrand',
  'Hugh',
  'Lothar',
  'Meroveus',
  'Pepin',
  'Ragnachar',
  'Sigebert',
  'Theuderic',
  'Waldemar',
  'Warinhari'
]

const FEMALE = [
  'Æthelflæd',
  'Æthelthryth',
  'Ælfgifu',
  'Cynethryth',
  'Eadburh',
  'Eadgifu',
  'Ealhswith',
  'Edith',
  'Godgifu',
  'Hild',
  'Leofgifu',
  'Mildthryth',
  'Osburh',
  'Seaxburh',
  'Sunngifu',
  'Wulfrun',
  'Adalind',
  'Adelaide',
  'Bathild',
  'Bertrada',
  'Brunhilda',
  'Clotilde',
  'Ermengarde',
  'Fredegund',
  'Gerberga',
  'Gisela',
  'Hildegard',
  'Hrodohaid',
  'Ida',
  'Kunigunde',
  'Mathilda',
  'Radegund',
  'Rotrude',
  'Sigilind',
  'Theudelinda',
  'Waldrada'
]

/** A random given name of the asked gender. */
export const randomName = (gender: 'M' | 'F'): string => {
  const list = gender === 'F' ? FEMALE : MALE
  return list[Math.floor(Math.random() * list.length)]
}
